language: node_js
os: osx # Better `headless-gl` support on macOS.
node_js:
  - "12" # Latest prebuilt binary for `headless-gl`
env:
  global:
    - CI=1
before_script:
  - yarn run dist
script:
  - yarn test
after_success:
  - yarn run coverage:report
